services:
  # Web service
  - type: web
    name: job_portal_exam
    env: python
    plan: starter
    buildCommand: "pip install poetry && poetry install"
    startCommand: "poetry run gunicorn job_portal_exam.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job_portal_exam_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: job_portal_redis
          type: redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9
      - key: DJANGO_SETTINGS_MODULE
        value: job_portal_exam.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
    
  # Redis service
  - type: redis
    name: job_portal_redis
    ipAllowList: 
      - source: 0.0.0.0/0
        description: everywhere
    plan: starter # Choose appropriate plan
    maxmemoryPolicy: allkeys-lru  # Recommended for caching