# Generated by Django 5.2.4 on 2025-09-22 07:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='question',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='id',
            field=models.CharField(default=core.models.generate_custom_schedule_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='examschedule',
            table='Schedules',
        ),
    ]
