# Generated by Django 5.2.4 on 2025-09-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_examschedule_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='exam_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
