# Generated by Django 5.2.4 on 2025-09-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_examschedule_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='core.examschedule'),
        ),
    ]
