# Generated by Django 5.0.6 on 2025-07-29 06:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=core.models.generate_custom_user_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
