# Generated by Django 5.2.4 on 2025-09-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examschedule',
            old_name='exam_time',
            new_name='exam_end_time',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='exam_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
