# Generated by Django 5.0.6 on 2025-07-29 07:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=core.models.generate_custom_job_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
