# Generated by Django 5.2.4 on 2025-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_exam_time_examschedule_exam_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='exam_end_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='exam_start_time',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
