# Generated by Django 5.0.6 on 2025-07-29 07:46

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=core.models.generate_application_id, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=30)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job')),
            ],
        ),
    ]
