# Generated by Django 5.0.6 on 2025-07-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_job_application_count_alter_user_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='name',
        ),
    ]
