# Generated by Django 5.0.6 on 2025-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_jobapplication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
