# Generated by Django 5.0.6 on 2025-07-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jobapplication_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='i am a singer', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.URLField(blank=True, default='https://claude.ai/chat/2862ceeb-0272-42b6-8740-fb3855822d7d', null=True),
        ),
    ]
