# Generated by Django 5.0.6 on 2025-07-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_bio_alter_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='default address', null=True),
        ),
    ]
