# Generated by Django 5.0.6 on 2025-07-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True, default='default location', null=True),
        ),
    ]
