# Generated by Django 5.0.6 on 2025-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
