# Generated by Django 5.0.6 on 2025-08-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(max_length=50),
        ),
    ]
