# Generated by Django 5.0.6 on 2025-08-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_plan_user_subscribe_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('legend', 'Legend'), ('ultra-legend', 'Ultra Legend')], default='free', max_length=20),
        ),
    ]
