# Generated by Django 5.0.6 on 2025-08-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
