# Generated by Django 5.0.6 on 2025-08-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='Jobs',
        ),
        migrations.AlterModelTable(
            name='jobapplication',
            table='Job_Applications',
        ),
    ]
