# Generated by Django 5.0.6 on 2025-08-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_job_table_alter_jobapplication_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
