# Generated by Django 5.0.6 on 2025-08-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_resume_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('inquiry', models.CharField(choices=[('general-inquiry', 'General Inquiry'), ('technical-support', 'Technical Support'), ('billing-question', 'Billing Question'), ('job-seeker-help', 'Job Seeker Help'), ('employer-support', 'Employer Support'), ('complaint', 'Complaint'), ('feedback', 'Feedback')], max_length=100)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
