# Generated by Django 5.0.6 on 2025-08-11 14:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.CharField(default=core.models.generate_custom_user_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
