# Generated by Django 5.0.6 on 2025-08-12 05:23

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.CharField(default=core.models.generate_custom_subscription_id, editable=False, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('razorpay_subscription_id', models.CharField(max_length=100, unique=True)),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subscribe_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('next_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
