# Generated by Django 5.0.6 on 2025-08-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
