# Generated by Django 5.0.6 on 2025-08-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
