# Generated by Django 5.0.6 on 2025-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_jobapplication_resume_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
