# Generated by Django 5.0.6 on 2025-08-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='main_resume_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
